import { createTypes } from 'reduxsauce';

export default createTypes(`
  PUSH_NEW_ROUTE
  REPLACE_ROUTE
  REPLACE_OR_PUSH_ROUTE
  POP_ROUTE
  POP_TO_ROUTE

  OPEN_DRAWER
  CLOSE_DRAWER

  SET_SPINNER_VISIBLE
  SET_LOCATION
  
  SET_USER
  SET_PRODUCTS
  SET_JOBS
  SET_BOOKINGS
    
  SET_AVATAR
  
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE
  
  SIGNUP_ATTEMPT
  SIGNUP_SUCCESS
  SIGNUP_FAILURE
  
  GET_USER_ATTEMPT
  GET_USER_SUCCESS
  GET_USER_FAILURE
  
  GET_NEW_REQUESTS_ATTEMPT
  GET_NEW_REQUESTS_SUCCESS
  GET_NEW_REQUESTS_FAILURE
  
  GET_FREELANCER_ATTEMPT
  GET_FREELANCER_SUCCESS
  GET_FREELANCER_FAILURE
  
  GET_RATINGS_ATTEMPT
  GET_RATINGS_SUCCESS
  GET_RATINGS_FAILURE
`);
